# Generated by Django 4.1.5 on 2023-01-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysteries", "0003_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="mystery",
            name="solution",
            field=models.TextField(default="The Snowman"),
            preserve_default=False,
        ),
    ]
