# Generated by Django 4.1.5 on 2023-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysteries", "0005_answer_correct_answer_reviewed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="correct",
            field=models.BooleanField(blank=True),
        ),
    ]
