# Generated by Django 4.1.5 on 2023-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysteries", "0006_alter_answer_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="correct",
            field=models.BooleanField(default=True),
        ),
    ]
