# Generated by Django 4.1.5 on 2023-01-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysteries", "0007_alter_answer_correct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="mystery",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="mysteries", to="mysteries.tag"
            ),
        ),
    ]
